# Generated by Django 5.0.3 on 2024-05-02 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lembremed', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='morador',
            options={'permissions': (('pode_gerenciar_morador', 'Pode gerenciar os moradores'), ('pode_medicar_morador', 'Pode administrar medicamentos nos moradores'))},
        ),
    ]
