# Generated by Django 5.0.3 on 2024-05-02 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lembremed', '0002_alter_morador_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profissional',
            options={'permissions': (('pode_gerenciar_profissional', 'Pode gerenciar os profissionales'),)},
        ),
    ]
