# Substituindo o MySQLdb pelo PyMySQL para compatibilidade com o ambiente de desenvolvimento.
# O pacote mysqlclient apresentou problemas de instalação, e o PyMySQL foi usado como alternativa.
import pymysql
pymysql.install_as_MySQLdb()
"""
Django settings for lembremed_proj project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-xp9qgxap%=7v%f4owi#6+2be6)!qavi)n!pwl(hpi@gg39^=!y'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'lembremed.apps.LembremedConfig',
]

MIDDLEWARE = [
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'lembremed_proj.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [
			os.path.join(BASE_DIR, 'templates'),
			#os.path.join(BASE_DIR, 'static'),  # Ajuste aqui para o caminho absoluto correto
			os.path.join(BASE_DIR, 'venv/Lib/site-packages/django/contrib/auth/templates')

		],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
			],
		},
	},
]

WSGI_APPLICATION = 'lembremed_proj.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.mysql',
		'NAME': 'lembremed',
		'USER': 'lembremed',
		'PASSWORD': 'g14UNIVESP',
		'HOST': '127.0.0.1',
		'PORT': '3306',
	}
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	{"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",},
	{"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",},
	{"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",},
	{"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",},
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
	('images', os.path.join(BASE_DIR, 'static', 'img')),
	('styles', os.path.join(BASE_DIR, 'static', 'styles')),
	('scripts', os.path.join(BASE_DIR, 'static', 'scripts')),
]

#Quando descomentar esta linha deve-se tbm descomentar a linha depois do array em urls.py
STATIC_ROOT = os.path.join(BASE_DIR, 'static_collected')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Redirect to home URL after login (Default redirects to /accounts/profile/)
LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = '/'

# Jogando os emails no console pra testar as funcionalidades
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_USE_TLS = True
# EMAIL_PORT = 587
# EMAIL_HOST_USER = #sender's email-id
# EMAIL_HOST_PASSWORD = #password associated with above email-id (not the regular password)



TELEGRAM_TOKEN = '8162836094:AAHQunZn3Vibglmi4OI8nCFBbsaviwBTXis'


#https://stackoverflow.com/questions/70910699/start-telegram-bot-on-django-project
#$ DJANGO_SETTINGS_MODULE=yourapp.settings telegram_bot.py