# Generated by Django 5.0.3 on 2024-04-30 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('cnpj', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('apresentacao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Morador',
            fields=[
                ('cpf', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('dt_nascimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('cpf', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('coren', models.IntegerField()),
                ('senha', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Substancia',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField(default=0)),
                ('qtd_minima', models.IntegerField(default=0)),
                ('dose', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('frequencia', models.IntegerField()),
                ('cpf_morador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morador.morador')),
            ],
        ),
        migrations.CreateModel(
            name='NomeComercial',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nome_comercial', models.CharField(max_length=100)),
                ('codigo_medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morador.medicamento')),
            ],
        ),
        migrations.CreateModel(
            name='Compoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_estoque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morador.estoque')),
                ('codigo_medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morador.medicamento')),
            ],
            options={
                'unique_together': {('codigo_estoque', 'codigo_medicamento')},
            },
        ),
        migrations.CreateModel(
            name='Administra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dthr_administracao', models.DateTimeField(null=True)),
                ('codigo_medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morador.medicamento')),
                ('cpf_morador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morador.morador')),
                ('cpf_profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morador.profissional')),
            ],
            options={
                'unique_together': {('cpf_profissional', 'cpf_morador', 'codigo_medicamento')},
            },
        ),
        migrations.CreateModel(
            name='Possui',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miligramagem', models.DecimalField(decimal_places=2, max_digits=8)),
                ('codigo_medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morador.medicamento')),
                ('codigo_substancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morador.substancia')),
            ],
            options={
                'unique_together': {('codigo_medicamento', 'codigo_substancia')},
            },
        ),
    ]
